spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/sourcemgr?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 6659968
    url: jdbc:sqlite:media.db
    driver-class-name: org.sqlite.JDBC

  servlet:
    multipart:
      max-file-size: 10Mb


server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:SqlMapping/*.xml
  type-aliases-package: com.chenkh.media.bean
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #config-location: mybatis-config.xml  #配置文件的路径